### ISSUE TITLE
老王你的库怎么一个类都没有啊

### ISSUE THREAD

**Issue by touero** [wangpengkaiReal/nnzy_Analyse#1]

**Comment by wangpengkaiReal** [comment]
在tool文件里面有一个啊，操作数据库的类




沉睡的狂虎
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangpengkaiReal/nnzy_Analyse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月27日(星期四) 下午5:52
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wangpengkaiReal/nnzy_Analyse] 老王你的库怎么一个类都没有啊 (Issue #1)

**Comment by touero** [comment]
来个客制化的行不行
